#!/usr/bin/env bash

set -e

# Bootstrap tpm (tmux plugin manager) if it is not installed yet.
# Neovim plugins are handled by lazy.nvim, which self-installs on first launch.
TPM_DIR="${HOME}/.tmux/plugins/tpm"
if [ ! -d "${TPM_DIR}" ]; then
    git clone https://github.com/tmux-plugins/tpm "${TPM_DIR}"
fi

CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"
