#!/usr/bin/env zsh

# For zsh plugin manager
if [ -f "$HOME/.zplug" ]; then
    curl -sL zplug.sh/installer | zsh
fi

# For vim plugin manger initialize
if [ -f "$HOME/.config/nvim/plug.vim" ]; then
    curl -fLo ~/.config/nvim/plug.vim --create-dirs \
        https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

set -e

CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"
